---
- name: "Create Master Instances"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ masters_qty }} format=master-%d
  vars:
    machine_type: "{{  master_machine_type }}"
    prefix: "master"
    docker_size: "{{ docker_storage_size }}"
    docker_storage: true
  when: masters

- name: "Create Infra Instances"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ infra_qty }} format=infra-%d
  vars:
    machine_type: "{{ infra_machine_type }}"
    prefix: "infra"
    docker_size: "{{ docker_storage_size }}"
    docker_storage: true
  when: infra

- name: "Create Node Instances"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ node_qty }} format=node-%d
  vars:
    machine_type: "{{ node_machine_type }}"
    prefix: "node"
    docker_size: "{{ docker_storage_size }}"
    docker_storage: true
  when: nodes

- name: "Create Storage Instances"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ storage_qty }} format=storage-%d
  vars:
    machine_type: "{{ gluster_machine_type }}"
    prefix: "storage"
    docker_storage: true
    docker_size: "{{ docker_storage_size }}"
    gluster_storage: true
    gluster_size: "{{ gluster_storage_size }}"
  when: storage

- name: "Create Master Load Balancer Instance"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ master_lb_qty }} format=master-lb-%d
  vars:
    machine_type: "{{ lb_machine_type }}"
    prefix: "master_lb"
    external_ip: "{{ master_lb_external_ip }}"
  when: master_lb

- name: "Create Infra Load Balancer Instance"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ infra_lb_qty }} format=infra-lb-%d
  vars:
    machine_type: "{{ lb_machine_type }}"
    external_ip: "{{ infra_lb_external_ip }}"
    prefix: "infra_lb"
  when: infra_lb

- name: "Create Bastion Instance"
  include_role:
    name: create_instance_gce
  with_sequence: start=1 end={{ bastion_qty }} format=bastion-%d
  vars:
    machine_type: "{{ bastion_machine_type }}"
    prefix: "bastion"
    docker_storage: false
    gluster_storage: false
    private_ip: true
  when: bastion